services:
  db:
    image: postgres:15
    container_name: info_about_book_api_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  book:
    build:
      context: .
    container_name: info_about_book_api
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["sh", "-c", "alembic upgrade head && python main.py --bind=0.0.0.0:8000"]
    ports:
      - 7777:8000